create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  birth_date date not null,
  zodiac text not null,
  seed bigint not null,
  numbers integer[] not null,
  reply text not null
);

alter table public.lotto_draws enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lotto_draws'
      and policyname = 'service role insert only'
  ) then
    create policy "service role insert only"
      on public.lotto_draws
      for insert
      to service_role
      with check (true);
  end if;
end $$;
